#!/usr/bin/env bun
/**
 * Sync Supabase connection config from the Supabase CLI (source of truth).
 *
 * - Resolves the linked project ref via `supabase projects list`
 * - Reads the publishable key via `supabase projects api-keys --project-ref <ref>`
 * - Writes apps/web/lib/supabaseConfig.generated.ts (gitignored)
 *
 * The web app never reads .env files for Supabase config; it imports the
 * generated module. Re-run any time via `bun run supabase:sync` (also chained
 * into dev/build/test scripts). Requires `supabase login`.
 *
 * Secret material is never printed: logs show only the ref, URL, and a masked
 * key prefix.
 */
import { spawnSync } from "node:child_process";
import { existsSync } from "node:fs";
import { writeFile } from "node:fs/promises";

const REPO_ROOT = new URL("../../../", import.meta.url).pathname;
const OUT_FILE = new URL("../lib/supabaseConfig.generated.ts", import.meta.url).pathname;
const PROJECT_NAME = "WebMCP-A11ySync";

function runCli(args: string[]): string {
  const res = spawnSync("bun", ["x", "supabase", ...args], {
    cwd: REPO_ROOT,
    encoding: "utf-8",
    timeout: 120_000,
  });
  if (res.status !== 0) {
    const detail = String(res.stderr ?? res.error?.message ?? "unknown error").slice(0, 400);
    throw new Error(`supabase ${args.join(" ")} failed: ${detail}`);
  }
  return String(res.stdout ?? "");
}

interface ProjectEntry {
  name?: string;
  ref?: string;
  id?: string;
  reference_id?: string;
}

interface ApiKeyEntry {
  name?: string;
  type?: string;
  api_key?: string;
}

function maskKey(key: string): string {
  return key.length > 20 ? `${key.slice(0, 18)}…(${key.length} chars)` : "(invalid length)";
}

function resolveProjectRef(): string {
  const out = runCli(["projects", "list", "-o", "json"]);
  const projects = JSON.parse(out) as ProjectEntry[];
  const match = projects.find((p) => p.name === PROJECT_NAME);
  const ref = match?.ref ?? match?.id ?? match?.reference_id;
  if (!ref) {
    const names = projects.map((p) => p.name ?? "?").join(", ");
    throw new Error(`Project "${PROJECT_NAME}" not found via CLI. Visible projects: ${names}`);
  }
  return ref;
}

function fetchPublishableKey(ref: string, reveal: boolean): string | null {
  const args = ["projects", "api-keys", "--project-ref", ref, "-o", "json"];
  if (reveal) args.push("--reveal");
  const out = runCli(args);
  const keys = JSON.parse(out) as ApiKeyEntry[];
  const pub =
    keys.find((k) => k.type === "publishable" && k.name === "default") ??
    keys.find((k) => k.type === "publishable");
  if (!pub?.api_key || !/^sb_publishable_[A-Za-z0-9_-]{20,}$/.test(pub.api_key)) return null;
  return pub.api_key;
}

function main(): Promise<void> {
  return (async () => {
    try {
      const ref = resolveProjectRef();
      let publishable = fetchPublishableKey(ref, false);
      if (!publishable) publishable = fetchPublishableKey(ref, true);
      if (!publishable) throw new Error("CLI did not return a valid publishable key.");
      const url = `https://${ref}.supabase.co`;
      const generated = `// GENERATED by Supabase CLI — do not edit by hand.
// Source: \`bunx supabase projects api-keys --project-ref ${ref}\`
// Refresh: \`bun run supabase:sync\` (requires \`supabase login\`)
// Generated: ${new Date().toISOString()}
export const SUPABASE_PROJECT_REF = ${JSON.stringify(ref)};
export const SUPABASE_URL = ${JSON.stringify(url)};
export const SUPABASE_PUBLISHABLE_KEY = ${JSON.stringify(publishable)};
`;
      await writeFile(OUT_FILE, generated, "utf-8");
      console.log(`Supabase CLI config synced: ref=${ref} url=${url} key=${maskKey(publishable)}`);
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      if (existsSync(OUT_FILE)) {
        console.warn(`supabase:sync failed (${msg}); keeping cached CLI config.`);
        return;
      }
      console.error(`supabase:sync failed and no cached config exists: ${msg}`);
      console.error("Run `bunx supabase login`, then retry.");
      process.exit(1);
    }
  })();
}

main();
